### ISSUE TITLE
example zfailover.lua problem

### ISSUE THREAD

**Issue by Ufoton** [memcached/memcached-proxylibs#5]
Hello,

There is problem when start this example - "memcached-proxy.lua:15: global 'poolset' is not callable (a nil value)"

memcached -o proxy_config=routelib.lua,proxy_arg=/etc/sysconfig/memcached-proxy.lua

**Comment by dormando** [comment]
@Ufoton just pushed a fix, thanks! Forgot to update the example after some updates.

**Comment by Ufoton** [comment]
thaks. work now
