### ISSUE TITLE
ptoblem with multiget

### ISSUE THREAD

**Issue by Ufoton** [memcached/memcached-proxylibs#6]
Hello, 
Problem with multiget from PHP. https://www.php.net/manual/en/memcached.getmulti.php
Even with mcp.CMD_ANY show error. this binary protocol is not supported?

**Comment by Ufoton** [comment]
simple scenario

<?php

$m = new Memcached();
$m->setOption(Memcached::OPT_BINARY_PROTOCOL, true);
$m->addServer('memcached', 11211);

$items = array(
    'key1' => 'value1',
    'key2' => 'value2',
    'key3' => 'value3'
);
$m->setMulti($items);
$result = $m->getMulti(array('key1', 'key3', 'badkey'));
var_dump($result);
?>

work without 
$m->setOption(Memcached::OPT_BINARY_PROTOCOL, true);

**Comment by dormando** [comment]
Sorry, binary protocol isn't supported by the proxy. :(

The binary protocol was deprecated in general in 1.6.0: https://github.com/memcached/memcached/wiki/ReleaseNotes160

The old text and new meta protocols are supported.

**Comment by dormando** [comment]
@Ufoton Were you able to get this working, or was binary protocol critical for you?

I'd like to close out the issue, thanks!

**Comment by Ufoton** [comment]
Hi @dormando 

Sorry I forgot to close the case. We are manage to switch to text protocol or redis. Symphony by default use binary only few components affected. 
Thanks
